
#.
#Parameters and abilities of Creatingspace's kinetic mechanisms
[kinetics]

	[kinetics.stressValues]

		#.
		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				legacy_mechanical_electrolyzer = 10000.0
				air_liquefier = 500.0
				catalyst_carrier = 8.0
				mechanical_electrolyzer = 2000.0

			#.
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v2.capacity]
				rocket_generator = 10000.0

#.
#
[rocketEngine]
	#.
	#.
	#the thrust in Newtons of the big engine
	#Range: > 0
	bigRocketEngineThrust = 4905000
	#.
	#the thrust in Newtons of the small engine
	#Range: > 0
	smallRocketEngineThrust = 98100
	#.
	# base ISP of rocket engines
	#Range: > 0
	methaloxISP = 365
	#.
	# reduction coefficient on the consumption
	#Range: 0.10000000149011612 ~ 3.4028234663852886E38
	ISPModifier = 1.5

